---
title: "Quiz 3"
author: "Francisco Martín"
date: "October 23, 2018"
output: html_document
---

## 1.-

Which of the following items is required for an R package to pass R CMD check without any warnings or errors?

- DESCRIPTION file (Correct)

- unit tests

- vignette

- a demo directory

- example data sets

Explanation -> Theory


## 2.-

Which of the following is a generic function in a fresh installation of R, with only the default packages loaded? (Select all that apply)

- lm

- show (Correct)

- mean (Correct)

- colSums

- dgamma

- predict (Correct)

Explanation -> Just type every method on console (without ())

## 3.-

What function is used to obtain the function body for an S4 method function?

- getClass()

- getMethod()   (Correct)

- showMethods()  

- getS3method()

Explanation -> Theory

## 4.-

Please download the R package DDPQuiz3 from the course web site. Examine the \verb|createmean|createmean function implemented in the R/ sub-directory. What is the appropriate text to place above the \verb|createmean|createmean function for Roxygen2 to create a complete help file?


- `
#' This function calculates the mean 
#' 
#' @param x is a numeric vector 
#' @return the mean of x 
#' @export 
#' @examples 
#' x <- 1:10 
#' createmean(x) 
` (Correct)


- `
#' This function calculates the mean 
#' 
#' @param x is a numeric vector 
#' @export 
#' @examples 
#' x <- 1:10 
#' createmean(x) 
`

- `
#' This function calculates the mean 
#' 
#' @param x is a numeric vector 
#' @export 
#' @examples 
#' x <- 1:10 
#' createmean(x) 
`

- `
#' This function calculates the mean 
#' 
#' @param x is a numeric vector 
#' @return the mean of x 
#' @export 
#' @examples 
#' x <- 1:10 
#' createmean(y) 
`

Explanation -> the only which makes sense